language: cpp
matrix:
  include:
      - os: linux
        dist: xenial
        sudo: required
        compiler: gcc
        addons:
          apt:
            sources:
              - sourceline: 'ppa:beineri/opt-qt-5.15.0-xenial'
              - sourceline: 'ppa:brightbox/ruby-ng'
            packages:
              # FPM dependencies
              - build-essential
              - ruby2.3
              - ruby2.3-dev
              # QT
              - qt515base
              - qt515multimedia
              - qt515tools
              - mesa-common-dev
              - libgl1-mesa-dev
              # PCap
              - libpcap-dev

        install:
            # Install FPM
            - cd install/linux/ && cp _FPM_Makefile Makefile && make package && sudo dpkg -i fpm*.deb && fpm --version && cd ../../
            # QT
            - source /opt/qt*/bin/qt*-env.sh
        script:
            - qmake
            - make -j$(nproc)
        after_success:
          - FILE=$(readlink -f install/linux/sACNView_*AppImage)
          - BASENAME=$(basename $FILE)
          - echo "Uploading $BASENAME to file.io..." && curl -sF "file=@$FILE" https://file.io | xargs printf "$BASENAME uploaded - %s\n"
          - FILE=$(readlink -f install/linux/sacnview_*.deb)
          - echo "Uploading $BASENAME to file.io..." && curl -sF "file=@$FILE" https://file.io | xargs printf "$BASENAME uploaded - %s\n"

      - os: osx
        osx_image: xcode11.6
        before_install:
          - chmod +x install/mac/sign-mac-executable.sh
          - ./install/mac/sign-mac-executable.sh
          - brew update
        install:
          # PCap
          - brew install libpcap
          # QT
          - brew install qt
          - brew link --force qt
          # Create-dmg
          - brew install create-dmg
        script:
          - qmake
          - make -j4
        after_success:
          - FILE=$(echo `pwd`/`ls install/mac/sACNView*.dmg`)
          - BASENAME=$(basename $FILE)
          - echo "Uploading $BASENAME to file.io..." && curl -sF "file=@$FILE" https://file.io | xargs printf "$BASENAME uploaded - %s\n"
