name: Build

on:
  push:
  pull_request:
  page_build:
  release:
    types:
      - created
      - edited
      - prereleased
      - released

jobs:
  build_linux:
  # Ubuntu Bionic
    runs-on: ubuntu-18.04

    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: Linux Environment Setup - install software-properties-common - ppa pre-req
      run: sudo apt-get install software-properties-common -y -qq 
    - name: Linux Environment Setup - install qt ppa
      run: sudo add-apt-repository ppa:beineri/opt-qt-5.15.2-bionic -y && sudo apt-get update -y
    - name: Linux Environment Setup - install python3
      run:  sudo apt-get install python3-pip --yes
    - name: Install QT 5.15.x - part 1
      run: sudo apt-get install qt5-default qt5-qmake qt515base qt515tools  -y
    - name: Install QT 5.15.x - part 2
      run: sudo /opt/qt515/bin/./qt515-env.sh
    - name: Create Makefile
      run:  |
        qtchooser -list-versions
        qmake -version
        qmake sACNView.pro
    - name: Run MakeFile
      run: make
    - name: upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: linux
        path: build/

  build_windows:
    runs-on: windows-latest

    steps:
    - name: MSVC Environment Setup
      uses: ilammy/msvc-dev-cmd@v1
    - name: checkout
      uses: actions/checkout@v2
    - name: Install Qt
      uses: jurplel/install-qt-action@v2.8.0
      with:
        version: '5.15.2'
    - name: Create Makefile
      run: 
        qmake sACNView.pro
    - name: Run MakeFile
      run: make
    - name: upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: windows
        path: build\ 


  build_mac:
    runs-on: macos-latest

    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: QT Environment Setup
      run:  |
        brew install qt5 qwt sfml
        brew link qt5 --force
    - name: Create Makefile
      run: qmake sACNView.pro
    - name: Run MakeFile
      run: make
    - name: upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: macos
        path: build/ 