name: Build

on:
  push:
  pull_request:
  page_build:
  release:
    types:
      - created
      - edited
      - prereleased
      - released

jobs:
  build_linux:
  # Ubuntu Bionic
    runs-on: ubuntu-18.04

    steps:
    - name: checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Linux Environment Setup - install software-properties-common - ppa pre-req
      run: sudo apt-get install software-properties-common -y -qq 
    - name: Linux Environment Setup - install python3
      run:  sudo apt-get install python3-pip --yes
    - name: Install Extra Packages
      run: sudo apt-get install mesa-common-dev libgl1-mesa-dev libpcap-dev -y
    - name: Install Qt
      uses: jurplel/install-qt-action@v2.14.0
      with:
        version: '5.15.2'
    - name: Create Makefile
      run:
        qmake sACNView.pro
    - name: Run MakeFile
      run: make
    - name: upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: linux
        path: build/

  build_windows:
    runs-on: windows-latest

    steps:
    - name: MSVC Environment Setup
      uses: ilammy/msvc-dev-cmd@v1
    - name: checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Install Qt
      uses: jurplel/install-qt-action@v2.14.0
      with:
        version: '5.15.2'
    # Parts of the breakpad install (gclient) need Python 2
    - name: Install Python2
    - uses: actions/setup-python@v2
      with:
        python-version: '2.x'
    - name: Create Makefile
      run: 
        qmake sACNView.pro
    - name: Run MakeFile
      run: nmake
    - name: upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: windows
        path: build\ 


  build_mac:
    runs-on: macos-latest

    steps:
    - name: checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Install Qt
      uses: jurplel/install-qt-action@v2.14.0
    - name: Create Makefile
      run: qmake sACNView.pro
    - name: Run MakeFile
      run: make
    - name: upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: macos
        path: build/ 